INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (1001, 'MBC-1 Matthew Bellamy', "Couleur : Matt Black, , Corps Tilleul, Vernis du corps finition mate, Manche en érable, Vernis du manche finition brillante, Touche Palissandre, Nombre de frettes 22, Diapason 25.5”, Radius compensé, Largeur au sillet 43 mm, Micro Manche simple bobinage Manson, Micro Chevalet double bobinage Manson, Sélecteur micros 3 positions, Contrôles Master Volume, Master Tone, Kill Switch, Mécaniques à blocage Cort, Accastillage Chrome, Cordes D'Addario®", 495.00, 'img/guitares/guitareselectrique/guitare001.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (1002, 'Classic Player Jazzmaster Special', "Couleur : Black, , Classic Player Series., , Corps aulne, Manche vissé en érable, Touche palissandre, Profil en 'C', 21 frettes Medium Jumbo, Diapason 25.5” (648 mm), Largeur au sillet 41 mm, Radius 9.5” (241mm), 2 micros Fender Special Design Hot Jazzmaster, Réglages “Lead” Circuit ( 2-Position Tone Switch - Volume - Tone ) “Rhythm” Circuit ( Volume - Tone ) Circuit Selector Switch, Vibrato Fender Adjusto-Matic + Lock Button, Mécaniques Fender/Ping Vintage Style, Accastillage chrome, Plaque 4 plis Brown Shell, Repères manches 'White Dots', Livrée en étui Deluxe Gig Bag", 1150.00, 'img/guitares/guitareselectrique/guitare002.jpg', 10, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (1101, 'Affinity Precision Bass PJ', "Couleur : Black, , Corps en aulne, manche érable, touche palissandre 20 cases, 1 micro type Precision, 1 micro type Jazz Bass, Réglages : volume 1, volume 2, tonalité, Chevalet à 4 pontets", 269.00, 'img/guitares/basseselectrique/basse001.jpg', 50, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (1102, 'TRBX174', "Couleur : Red Metallic, La nouvelle TRBX174 est la dernière arrivée de cette incroyable et innovante série de basses électriques TRBX. Ce modèle idéal pour débuter, offre confort de jeu, équillibre et légèreté", 249.00, 'img/guitares/basseselectrique/basse002.jpg', 30, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (2001, 'BATTERIE STANDARD PEARL - ROAD SHOW STANDARD 22" 5 FÛTS JET BLACK', "Batterie acoustique Road Show 22” 5 fts 100% peuplier de 9 plis/7mm, livre avec 1 pdale de grosse caisse P-63-J,1 sige D-60 et 1 set de cymbales Pearl. Avec son pack d'accessoires inclus, c'est la batterie idale pour raliser ses premires frappes. Coloris Jet Black", 499.00, 'img/batteries/batteriesacoustique/batterie001.jpg', 7, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (2002, 'BATTERIE FUSION PEARL - PEARL EXPORT FUSION 20" 5 FÛTS SMOKEY CHROME', "Batterie acoustique Pearl Export Fusion 20” 5 fts Smokey Chrome. Le retour de la batterie la plus vendue de l'histoire ! Ici en bundle avec en plus pédale Demonator et un pack de cymbales Zildjian Planet Z. © SonoVente.com :http://www.sonovente.com/pearl-pearl-export-fusion-20-5-futs-smokey-chrome-p45675.html", 759.00, 'img/batteries/batteriesacoustique/batterie002.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (2101, 'BATTERIE ELECTRONIQUE ALESIS - DM LITE', 'Batterie Electronique Alesis de rfrence ! La Aledis DM LITE : Un prix ultra abordable pour une qualité et un ralisme incroyable ! Un module de 200 sons', 279, 'img/batteries/batterieselectrique/batterie001.jpg', 30, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (2102, 'BATTERIE ELECTRONIQUE ALESIS - DM NITRO', "Kit de batterie électronique complet avec un module compos de 10 kits pré-programmés, 30 morceaux d’accompagnement, 200 sons, port USB pour utilisation sur logiciel...grâce ses pads en caoutchouc, elle procure la même sensation qu'une batterie acoustique ! Un grand confort de jeu, des performances tonnantes, un prix qui l'est encore plus, une superbe affaire pour dbutant ou entraînement la maison !", 419.00, 'img/batteries/batteriesacoustique/batterie002.jpg', 10, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (3001, 'KEILBERG ETUDE NL', "Piano d'étude de bonne qualité, conçu sur une structure tout à fait traditionnelle, son prix très modeste est le principal atout", 2350.00, 'img/pianos/pianodroit/piano001.jpg', 4, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (3002, 'FORSTER AUGUST 125G Noir brillant', "Dans la lignée des plus grands facteurs de pianos au monde. L'équilibre et la précision du toucher permettent aux plus exigeants de s'exprimer pleinement dans tous les registres", 16360.00,  'img/pianos/pianodroit/piano002.jpg', 0, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (3101, 'SYNTHÉTISEUR YAMAHA - REFACE CS', "Piano analogique modélisation physique compact doté de 37 mini-touches, intégrant plusieurs types de synthèse et d’oscillateurs dans un élégant boîtier compact. Gros sons mono/poly, facilité d'utilisation, mobilité, mini-touches HQ assurant un toucher précis et une excellente réponse, pour un jeu rapide et naturel... un contrôle simple, des sons colorés, une dynamique impressionnante", 399.00, 'img/pianos/synthetiseur/synthe001.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (3102, 'SYNTHÉTISEUR ROLAND - TB-03 ROLAND BOUTIQUE', "Synthétiseur modulaire qui a le comportement et les sons TB-303 authentiques grâce la technologie ACB de Roland, qui propose aussi un séquenceur TB classique aux nouvelles fonctionnalités, de nouvelles fonctionnalités par rapport l'original comme la possibilité de connexions d'autres instruments, une interface audio USB pour enregistrement direct et l'alimentation par piles ou USB. Le classique TB-303 dans la paume de votre main !", 399, 'img/pianos/synthetiseur/synthe001.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (4001, 'SubZero microphone Vocal dynamique SZM-11', "Le Subzero SZM-11 microphone vocal est un appareil idéal pour enregistrer ou amplifier des voix mâles et femelles. Ce microphone doté d'une bande passante large et parfaitement colorée, reprend la voix proprement et authentiquement. Intégré dans un boîtier métallique robuste, avec la grille et capsule antichoc, ce microphone est incroyablement durable.", 29.35, 'img/studio/microphone/micro001.jpg', 50, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (4002, 'Cravate Studio dynamique USB Mic', "Le micro cravate Studio dynamique USB est un microphone dynamique de haute qualité, doté d'une protection anti-pop intégrée et interrupteur marche/arrêt. Ce microphone dynamique qualité branchera directement sur votre ordinateur, vous permettant de capturer des enregistrements vocaux de qualité à la volée. Ce microphone compatible classe se connecte via un câble USB standard (fourni) avec une fréquence d'échantillonnage ou 44,1 et 48 kHz. La large bande passante le rend parfait pour la capture des enregistrements de qualité chaque fois que vous avez besoin. Le micro cravate Studio dynamique USB est également livré avec un trépied, attache de microphone et un câble USB pour vous aider à démarrer.", 39.95, 'img/studio/microphone/micro002.jpg', 60, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (4101, 'Adam A77X Active paire de moniteurs de Studio, avec Stands', "Le tout nouveau A77X, en raison de ses caractéristiques exceptionnelles, pourrait devenir un vrai jeu de changeur : équipé avec les mêmes technologies avancées comme les A7X, c'est donc très similaire à l'haut-parleur bidirectionnel. L'A77X, cependant, se distingue par beaucoup de niveaux de pression acoustique maximal supérieur et sans compression et dynamique. Grâce à ses caractéristiques de puissance et de rayonnement, il est également parfaitement adapté à la fois proche et la surveillance du milieu de terrain. Ce pack comprend une paire de moniteurs de studio Adam Audio A77X et Gear4music moniteur se tient.", 1738.00, 'img/studio/moniteur/moniteur001.jpg', 7, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (4102, 'Numark DJ N ondes 580 L système de monitoring', "Le Numark N ondes 580 L DJ Monitoring System offre 80 watts (2 x 40 watt) de son puissant et symétrique idéal pour la production domestique de DJ. Avec 5,25 & rdquo ; haut-parleurs de graves, 1 & rdquo ; tweeters à dôme, lumineux 3 lumières de couleur LED et connectivité RCA/jack TRS N ondes 580L moniteurs peuvent être connectés à une gamme des installations de studio et disposent d'une construction robuste de MDF de soie. Par ailleurs N ondes 580L moniteurs incluent un éclairage LED avec trois couleurs vives (vert, bleu et rouge) et trois modes de fonctionnement (palpitent, ralentir le cycle et arrêt).", 149.99, 'img/studio/moniteur/moniteur002.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (5001, 'YAMAHA YSP-1400 Noir Barre de son 5.1 - Bluetooth', "Barre de son 5.1 Bluetooth - Système Surrounf frontal - Bluetooth et application dédiée pour contrôle via smartphone - Technologie Digital Sound Projector pour un son surround authentique - Double subwoofer intégré pour des basses riches - Amplification et décodages intégrés", 244.99, 'img/sono/barreson/barreson001.jpg', 40, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (5002, 'Philips HTS7140', "Barre de son - Sortie HDMI - Port Ethernet - Tuner FM RDS - Technologie Ambisound - DTS HD - Dolby TrueHD - Lecture de disques Blu-Ray - BD Live - Compatible Full HD 3D - Suréchantillonage vidéo - Garantie 2 ans", 1829.13, 'img/sono/barreson/barreson002.jpg', 14, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (5101, 'Restio MusicCast ISX-18D', "Décorez votre espace de vie et profitez de votre musique. Posez l’ISX-18D sur une étagère ou accrochez-le au mur, pour joindre l’utile à l’agréable. Combinez-le avec le système audio multi-room Yamaha MusicCast pour accéder simplement à une large gamme de sources. L’ISX-18D développe votre univers musical, toujours avec élégance.", 379.00, 'img/sono/sysaudio/sysaudio001.jpg', 16, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (5102, 'TSX-B235', 'Avec ses contours arrondis et son panneau en boix naturel, la nouvelle station d’accueil Bluetooth TSX-B235 de Yamaha procure un sentiment de sérénité et de bien-être. Equipée de nombreuses entrées audio dont un lecteur CD, une entrée USB et un récepteur Bluetooth, elle permet de profiter de sa musique quelque soit le support. Audio et intérieur sont enfin en parfaite harmonie.', 379.99, 'img/sono/sysaudio/sysaudio002.jpg', 0, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (6001, 'CLF Tricolor Mini Par spot à LED RGB', "Ce PAR est équipé de 7 modules Tri-LED RGB puissants qui fournissent un rendement lumineux élevé. Son faisceau d'un angle de 30 degrés vous permet d'éclairer une large surface ou d'être utilisé pour des effets lumineux particulièrement efficaces. Avec son coupe-flux optionnel, vous pourrez projeter avec précision le faisceau lumineux sur votre scène.", 139.00, 'img/eclairage/lampes/lampe001.jpg', 20, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (6002, 'American DJ COB Cannon Wash Pearl projecteur', "Le COB Cannon Wash d’ADJ utilise la technologie avancée de COB-LEDs (Chip-On-Board) permettant de placer une source LED puissante sur un espace très réduit. En résulte un PAR à LED puissant avec un mélange de couleurs RGBA tèrs fluide et homogène sans ombres RGBA. Conçu pour l’utilisation comme projecteur WASH sur les scènes, les clubs, les pistes de danse ou dans les églises, sa double lyre de suspension lui permet aussi d’être placé au sol et utilisé comme Wash mural ou plafonnier", 299.00, 'img/eclairage/lampes/lampe002.jpg', 50, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (6101, "JB systems Party Bar set d'éclairage multiFX", "Avec le set Party Bar de JB Systems, vous êtes paré pour toutes les fêtes. Le set Party Bar réunit sur une même structure quatre jeux de lumière à LED et non des moindres. En effet, la structure est équipée de deux effets rotatifs Derby avec des LED RGB de 3 watts, de deux projecteurs avec trois LED RGB de 9 watts avec un angle de rayonnement de 15 degrés, de quatre LED blanches froides qui servent à créer l'effet stroboscope et blinder et même d'un laser bicolore rouge et vert. Pour compléter l'ensemble, vous recevrez également une télécommande sans fil, un étui de rangement, un adaptateur pour pied de 35 mm et des supports de suspension. La seule chose qu'il vous reste à acquérir est un pied et un interrupteur d'arrêt d'urgence interlock pour le laser. Pour résumer, il s'agit d'un set d'éclairage complet disponible à un prix plus que raisonnable.", 359.00, 'img/eclairage/setlampes/set001.jpg', 14, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (6102, "Bax Kit débutant éclairage 2", "Il s'agit d'un kit de base très facile à utiliser et accessible à tous les débutants. C'était le but principal que bax-shop s'est fixé lors de la composition de ces kits débutants. Destiné aussi bien aux DJ débutants qu'aux futurs responsables lumière, voici le kit débutant éclairage. Les éléments de base de ce kit sont deux scanners à LED ALO Duo Roll de la marque Ayra. Ils sont équipés de deux LED RGBW de 10 watts et d'un système rotatif spécial muni de miroirs, ce qui vous permet de diffuser des faisceaux lumineux aux quatre coins de la salle. Pour amplifier l'impact des faisceaux lumineux, une machine à fumée est l'outil idéal. Nous avons donc ajouté dans ce kit le modèle WSM01 MKIII, une machine à fumée puissante de 900 watts.", 344.00, 'img/eclairage/setlampes/set002.jpg', 36, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (7001, "DateQ XTC-2 table de mixage DJ", "Le XTC-2 est le successeur de la célèbre table de mixage DJ DateQ XTC. La deuxième version est évidement plus étendue que le premier modèle, mais elle a gardé la parfaite sonorité analogique qui a consolidé la réputation de la première version. Le XTC-II est une table de mixage «battle» compacte de 4+1 canaux à laquelle on peut connecter jusqu'à 9 sources sonores. Grâce à ce grand nombre de connexions, vous pouvez brancher des platines et des lecteurs CD en même temps et vous n'aurez plus besoin de les débrancher pour alterner entre les deux. Le bouton de chaque canal vous permet de choisir la source sonore désirée. Cette option rend ce XTC-II de DateQ idéal pour les clubs. De plus, cette console dispose d'une option envoi/retour FX pour l'utilisation d'un appareil d'effets externe. Pour chaque canal, vous pouvez choisir si vous voulez utiliser des effets ou non. Le mixage des canaux se fait à l'aide des faders de 60 mm à commande VCA, ce qui exclut les interférences. La courbe du X-fader est réglable, ce qui permet de créer une vraie transition «house» ou «scratch» ultra rapide. Vous pouvez faire une pré-écoute sur chaque canal où vous entendrez le canal en question en combinaison avec le canal master. Votre DateQ peut être branché sur une sono à l'aide des sorties XLR symétriques. Ces dernières sont en outre protégées par un limiteur à réglage numérique, afin que le niveau d'entrée soit toujours envoyé sans distorsions.", 579.00, 'img/DJ/tablemixage/tablemix001.jpg', 32, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (7002, "Behringer DJX 750 pro table de mixage DJ professionnelle 12 pouces", "Ce moment est enfin arrivé: le digne successeur du DJX 700! Ce DJX 750 est une table de mixage DJ à cinq voies avec une collection d’effets numériques 24 bits avec un contrôle de paramètre avancé. Cette console est idéale pour les DJ débutants désirants un bon équipement pour un petit budget. Elle dispose d’un double compteur BPM intelligent avec écran de synchronisation de rythme et de faders ultra souples qui font un Behringer si populaire.", 184.00, 'img/DJ/tablemixage/tablemix002.jpg', 16, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (7101, 'Stanton T62B platine vinyle direct drive', "Ceux qui travaillent toujours avec une platine vinyle veulent en tirer le meilleur parti. La qualité et la facilité d’utilisation de cette platine Stanton est appréciée de tous. Elle convient parfaitement pour le scratch et grâce à son bras droit et sa cellule de qualité, son diamant restera dans le sillon, même durant les plus gros mixes. En bref, une platine qui fait exactement ce qu'on lui demande et ce qu'on attend d'elle.", 249.00, 'img/DJ/platine/platine001.jpg', 19, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (7102, 'Stanton ST-150 Platine vinyle', 'En créant le ST-150, Stanton est retourné dans le temps et a reconstruit la base, cette platine vinyle est tout ce dont un professionnel DJ a besoin. Cette platine dispose d’un moteur puissant, idéale pour le travail de DJ. Il possède en plus de ce moteur, un bras de tonalité S et un diamant Trackmaster.', 649.00, 'img/DJ/platine/platine002.jpg', 15, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (8001, 'Etui guitare EGC100 BL', 'Etui pour guitare électrique type stratocaster, telecaster... Fabrication traditionnelle en bois multiplis, solide et durable. Revêtement en vinyle simili cuir noir résistant. Fermetures et charnières en métal. Intérieur velours noir. Dimensions intérieures (en mm) : Longueur : 995, Largeur : 329, Hauteur : 60.', 59.00, 'img/cases/casesmusique/casemusique001.jpg', 45, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (8002, '1SKB-4 ETUI GUITARE BASSE LECTRIQUE', "Membre de la gamme des étuis SKB Economy, ce modèle rectangulaire dispose d'un intérieur doublé en peluche EPS deluxe, représentant un rapport qualité-prix exceptionnel. Le modèle 1SKB-4 a été conçu pour contenir toute une gamme de guitares basses électriques pour guitariste droitier.", 134.00, 'img/cases/casesmusique/casemusique002.jpg', 32, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (8101, 'Stagg SCF-522819 valise 521 x 278 x 190,8 mm', "", 219.00, 'img/cases/caseseclairage/case001.jpg', 19, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (8102, 'Stagg SCF-333517 valise 334 x 347 x 168 mm', "", 110.00, 'img/cases/caseseclairage/case002.jpg', 31, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (9001, 'TC Electronic Polytune Clip accordeur', "", 42.00, 'img/accessoires/accordeurs/accordeur001.jpg', 60, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (9002, 'Fazley T-60 accordeur chromatique', "", 6.90, 'img/accessoires/accordeurs/accordeur002.jpg', 0, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (9101, 'Innox ILA 01 pupitre', "", 99.00, 'img/accessoires/pupitres/pupitre001.jpg', 30, 20, true);
INSERT INTO avg_produit (`code_produit`,`libelle_court_produit`,`libelle_long_produit`,`prix_vente_produit`,`photo_produit`,`quantite_stock`,`tva_produit`,`actif_produit`) VALUES (9102, 'Innox ISA 01 pupitre avec plateau perforé', "", 13.90, 'img/accessoires/pupitres/pupitre002.jpg', 90, 20, true);


INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1001, 10);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1002, 10);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1101, 11);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1102, 11);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2001, 12);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2002, 12);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2101, 13);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2102, 13);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3001, 14);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3002, 14);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3101, 15);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3102, 15);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4001, 16);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4002, 16);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4101, 17);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4102, 17);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5001, 18);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5002, 18);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5101, 19);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5102, 19);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6001, 20);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6002, 20);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6101, 21);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6102, 21);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7001, 22);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7002, 22);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7101, 23);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7102, 23);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8001, 24);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8002, 24);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8101, 25);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8102, 25);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9001, 26);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9002, 26);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9101, 27);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9102, 27);

INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1001, 1);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1002, 1);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1101, 1);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (1102, 1);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2001, 2);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2002, 2);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2101, 2);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (2102, 2);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3001, 3);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3002, 3);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3101, 3);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (3102, 3);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4001, 4);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4002, 4);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4101, 4);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (4102, 4);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5001, 5);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5002, 5);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5101, 5);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (5102, 5);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6001, 6);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6002, 6);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6101, 6);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (6102, 6);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7001, 7);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7002, 7);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7101, 7);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (7102, 7);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8001, 8);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8002, 8);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8101, 8);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (8102, 8);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9001, 9);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9002, 9);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9101, 9);
INSERT INTO avg_fait_parti (`code_produit`, `code_rubrique`) VALUES (9102, 9);





















